# Generated by Django 5.2.9 on 2025-12-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="hello", max_length=50),
            preserve_default=False,
        ),
    ]
